name = "ViperPkg"
uuid = "d7e4f8a0-5c3b-4d9e-8f2a-1b3c4d5e6f7a"
authors = ["Jonathan D.A. Jewell <jonathan.jewell@open.ac.uk>"]
version = "0.1.0"

[deps]
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
Tar = "a4e569a6-e804-4fa4-b0f3-eef7a1d5b13e"

[compat]
julia = "1.10"
HTTP = "1.10"
JSON3 = "1.14"
